---
- name: Generate CA for Self Signed Certs
  connection: local
  hosts: 127.0.0.1
  tags: certificate_authority
  tasks:
  - import_role:
      name: confluent.variables_handlers

  - name: Create Certificate Authority and Copy to Ansible Host
    include_tasks: tasks/certificate_authority.yml
    when: (self_signed|bool and regenerate_ca|bool and kafka_broker_listeners | ssl_required(ssl_enabled)) or create_mds_certs|bool

- name: Host Prerequisites
  connection: local
  hosts: 127.0.0.1
  tags: common
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.common

- name: Zookeeper Provisioning
  connection: local
  hosts: 127.0.0.1
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.zookeeper

- name: Kafka Broker Provisioning
  connection: local
  hosts: 127.0.0.1
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_broker

- name: Schema Registry Provisioning
  connection: local
  hosts: 127.0.0.1
  tags: schema_registry
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.schema_registry

- name: Kafta Connect Provisioning
  connection: local
  hosts: 127.0.0.1
  tags: kafka_connect
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_connect

- name: KSQL Provisioning
  connection: local
  hosts: 127.0.0.1
  tags: ksql
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.ksql

- name: Kafka Rest Provisioning
  connection: local
  hosts: 127.0.0.1
  tags: kafka_rest
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_rest

- name: Control Center Provisioning
  connection: local
  hosts: 127.0.0.1
  tags: control_center
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.control_center
